services:
  feedback-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: tzr-feedback-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - tzr-network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*main.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  tzr-network:
    driver: bridge
